export interface IOffer {
    name: string,
    inventoryMaxValue: number,
    inventoryValue: number,
    showInventoryValue: boolean,
    price: number,
    sellerId: string,
    sellerName: string,
    offererId: string,
    offererName: string,
    eventId: string,
    eventName: string,
    validFrom: any,
    validThrough: any,
    categoryId: string,
    categoryName: string,
}