<template>
    <div>
        <ul>
            <li>
                追蹤與訂閱的講者或主辦
                這邊會是個月例
            </li>
            <li>
                取消訂閱也在這
            </li>
            <li></li>
        </ul>
    </div>
</template>